suite: test secrets
release:
    name: my-release
templates:
    - secret.yaml
tests:
    - it: tests defaults
      asserts:
          - isKind:
                of: Secret
          - equal:
                path: apiVersion
                value: v1
          - equal:
                path: metadata.name
                value: my-release-github-rate-limits-exporter
          - equal:
                path: metadata.labels.app\.kubernetes\.io/name
                value: my-release-github-rate-limits-exporter
          - matchRegex:
                path: metadata.labels.helm\.sh/chart
                pattern: github-rate-limits-exporter-\d+\.\d+\.\d+
          - equal:
                path: metadata.labels.app\.kubernetes\.io/instance
                value: my-release
          - equal:
                path: metadata.labels.app\.kubernetes\.io/managed-by
                value: Helm
          - matchRegex:
                path: metadata.labels.app\.kubernetes\.io/version
                pattern: \d+\.\d+\.\d+
          - isNull:
                path: data
    - it: set secrets
      set:
          exporter:
              github:
                  accountName: theodore86
                  token: $$#dsdsdd#@345GGGF
                  appID: 123456
                  installationID: 1234567
                  privateKey: |
                      tw3JrKIjFxIMBd9Q+DxqmMX4f8Ro6NGDQZkb/I5jC84RStRNwn6vbQ5kk8PthDzI
      asserts:
          - equal:
                path: data.accountName
                value: dGhlb2RvcmU4Ng==
          - equal:
                path: data.token
                value: JCQjZHNkc2RkI0AzNDVHR0dG
          - equal:
                path: data.appID
                value: JSFkKGZsb2F0NjQ9MTIzNDU2KQ==
          - equal:
                path: data.installationID
                value: JSFkKGZsb2F0NjQ9MS4yMzQ1NjdlKzA2KQ==
          - equal:
                path: data.privateKey
                value: dHczSnJLSWpGeElNQmQ5UStEeHFtTVg0ZjhSbzZOR0RRWmtiL0k1akM4NFJTdFJOd242dmJRNWtrOFB0aER6SQo=
