suite: test serviceaccount
release:
  name: my-release
templates:
  - serviceaccount.yaml
tests:
  - it: tests defaults
    asserts:
      - isKind:
          of: ServiceAccount
      - equal:
          path: apiVersion
          value: v1
      - equal:
          path: metadata.name
          value: my-release-github-rate-limits-exporter
      - equal:
          path: metadata.labels.app\.kubernetes\.io/name
          value: my-release-github-rate-limits-exporter
      - matchRegex:
          path: metadata.labels.helm\.sh/chart
          pattern: github-rate-limits-exporter-\d+\.\d+\.\d+
      - equal:
          path: metadata.labels.app\.kubernetes\.io/instance
          value: my-release
      - equal:
          path: metadata.labels.app\.kubernetes\.io/managed-by
          value: Helm
      - matchRegex:
          path: metadata.labels.app\.kubernetes\.io/version
          pattern: \d+\.\d+\.\d+
      - isNull:
          path: metadata.annotations
