suite: test service
release:
  name: my-release
templates:
  - service.yaml
tests:
  - it: test defaults
    asserts:
      - isKind:
          of: Service
      - equal:
          path: apiVersion
          value: v1
      - equal:
          path: metadata.name
          value: my-release-github-rate-limits-exporter
      - isNull:
          path: metadata.annotations
      - equal:
          path: spec
          value:
            ports:
              - name: metrics
                port: 80
                protocol: TCP
                targetPort: metrics
            selector:
              app.kubernetes.io/name: my-release-github-rate-limits-exporter
              app.kubernetes.io/instance: my-release
            type: ClusterIP
  - it: set labels, annotations, port, and clusterIP
    set:
      service:
        labels:
          label: label-value
        annotations:
          key: value
        clusterIP: 10.10.10.11
        port: 8080
    asserts:
      - equal:
          path: metadata.labels.label
          value: label-value
      - equal:
          path: metadata.annotations
          value:
            key: value
      - equal:
          path: spec
          value:
            clusterIP: 10.10.10.11
            ports:
              - name: metrics
                port: 8080
                protocol: TCP
                targetPort: metrics
            selector:
              app.kubernetes.io/name: my-release-github-rate-limits-exporter
              app.kubernetes.io/instance: my-release
            type: ClusterIP
