---
apiVersion: 1
prune: true
datasources:

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    uid: PBFA97CFB590B2093
    isDefault: true
    editable: true
---
