---
nameOverride: ""
fullnameOverride: ""

exporter:
  image: theodore86/prometheus-gh-rate-limit-exporter
  tag: v0.7.1
  pullPolicy: Always
  port: 10050
  github:
    accountName: ""
    authType: app
    appID: ""
    installationID: ""
    mountPath: /secret
    privateKey: |
      ""

service:
  type: ClusterIP
  clusterIP: ""
  port: 80
  annotations: {}
  labels: {}

replicaCount: 1

terminationGracePeriodSeconds: 30

imagePullSecrets: []

serviceAccount:
  create: true
  annotations: {}

serviceMonitor:
  enabled: false

resources:
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    memory: 512Mi

podLabels: {}

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

tolerations: []

affinity: {}

nodeSelector: {}
