---
nameOverride: ""
fullnameOverride: ""

exporter:
  image: theodore86/prometheus-gh-rate-limit-exporter
  tag: v0.7.1
  pullPolicy: Always
  port: 10050
  github:
    accountName: ""
    authType: pat
    token: ""

service:
  type: ClusterIP
  clusterIP: ""
  port: 80
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io.scheme: "http"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "80"
  labels: {}

replicaCount: 1

terminationGracePeriodSeconds: 30

imagePullSecrets: []

serviceAccount:
  create: true
  annotations: {}

serviceMonitor:
  enabled: false

resources:
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    memory: 512Mi

podLabels: {}

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

tolerations: []

affinity: {}

nodeSelector: {}
