---
global:
  scrape_timeout: 5s

rule_files:
  - rules/alerts.yml

scrape_configs:
  - job_name: prometheus
    scrape_interval: 40s
    metrics_path: /metrics
    static_configs:
      - targets:
          - "prometheus:9090"

  - job_name: gh-rl-exporter
    scrape_interval: 30s
    metrics_path: /
    static_configs:
      - targets:
          - "gh-rl-exporter:10050"

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ["alertmanager:9093"]
