{
 "title": "Github Core API Rate Limits",
 "tags": [
  "github",
  "monitoring"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "account",
    "label": "account",
    "query": {
     "query": "label_values(github_rate_limits_core{type=~\"used|limit|remaining\"}, account)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Github API Rate Limits (Time to) Reset",
   "type": "table",
   "description": "The time at which the current Github API Rate Limit window resets.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "label_join(sum by (__name__) ({type=\"reset\"}), \"Metric\", \"\", \"__name__\") * 1000",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Integration Manifest API Rate Limits",
   "type": "gauge",
   "description": "Grafana dashboard to monitor Github Integration Manifest API Rate Limits",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "github_rate_limits_integration_manifest{account=\"$account\", type=~\"limit|remaining|used\"}",
     "legendFormat": "Integrate Manifest API - {{type}}"
    }
   ]
  },
  {
   "title": "Github GraphQL API Rate Limits",
   "type": "bargauge",
   "description": "Grafana dashboard to monitor Github GraphQL API Rate Limits",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "github_rate_limits_graphql{account=\"$account\", type=~\"limit|remaining|used\"}",
     "legendFormat": "GraphQL API - {{type}}"
    }
   ]
  },
  {
   "title": "Github Core API Rate Limits",
   "type": "bargauge",
   "description": "Grafana dashboard to monitor Github Core API Rate Limits",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "github_rate_limits_core{account=\"$account\", type=~\"limit|remaining|used\"}",
     "legendFormat": "Core API - {{type}}"
    }
   ]
  },
  {
   "title": "Github Search API Rate Limits",
   "type": "state-timeline",
   "description": "Grafana dashboard to monitor Github Search API Rate Limits",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "github_rate_limits_search{account=\"$account\", type=~\"limit|remaining|used\"}",
     "legendFormat": "Search API - {{type}}"
    }
   ]
  },
  {
   "title": "Github API Code Scanning Upload Rate Limits",
   "type": "stat",
   "description": "Grafana dashboard to monitor the retrieval and update of the code scanning alerts from a Github repository",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "github_rate_limits_code_scanning_upload{account=\"$account\", type=~\"limit|remaining|used\"}",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}