kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: worker
  image: kindest/node:v1.26.3@sha256:61b92f38dff6ccc29969e7aa154d34e38b89443af1a2c14e6cfbd2df6419c66f
  extraPortMappings:
    # Prometheus
  - containerPort: 30000
    hostPort: 30000
    # Grafana
  - containerPort: 31000
    hostPort: 31000
    # AlertManager
  - containerPort: 32000
    hostPort: 32000
    # Node exporter
  - containerPort: 32001
    hostPort: 32001
- role: control-plane
  image: kindest/node:v1.26.3@sha256:61b92f38dff6ccc29969e7aa154d34e38b89443af1a2c14e6cfbd2df6419c66f
