kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: worker
  image: kindest/node:v1.29.12@sha256:62c0672ba99a4afd7396512848d6fc382906b8f33349ae68fb1dbfe549f70dec
  extraPortMappings:
    # Prometheus
  - containerPort: 30000
    hostPort: 30000
    # Grafana
  - containerPort: 31000
    hostPort: 31000
    # AlertManager
  - containerPort: 32000
    hostPort: 32000
    # Node exporter
  - containerPort: 32001
    hostPort: 32001
- role: control-plane
  image: kindest/node:v1.29.12@sha256:62c0672ba99a4afd7396512848d6fc382906b8f33349ae68fb1dbfe549f70dec
