kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: worker
  image: kindest/node:v1.25.3@sha256:f52781bc0d7a19fb6c405c2af83abfeb311f130707a0e219175677e366cc45d1
  extraPortMappings:
    # Prometheus
  - containerPort: 30000
    hostPort: 30000
    # Grafana
  - containerPort: 31000
    hostPort: 31000
    # AlertManager
  - containerPort: 32000
    hostPort: 32000
    # Node exporter
  - containerPort: 32001
    hostPort: 32001
- role: control-plane
  image: kindest/node:v1.25.3@sha256:f52781bc0d7a19fb6c405c2af83abfeb311f130707a0e219175677e366cc45d1
