---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "github-rate-limits-exporter.fullname" . }}
  labels:
    {{- include "github-rate-limits-exporter.labels" . | nindent 4 }}
data:
  {{- if .Values.exporter.github.accountName }}
  accountName: {{ .Values.exporter.github.accountName | b64enc }}
  {{- end }}
  {{- if .Values.exporter.github.token }}
  token: {{ .Values.exporter.github.token | b64enc }}
  {{- end }}
  {{- if .Values.exporter.github.appID }}
  appID: {{ printf "%d" .Values.exporter.github.appID | b64enc }}
  {{- end }}
  {{- if .Values.exporter.github.installationID }}
  installationID: {{ printf "%d" .Values.exporter.github.installationID | b64enc }}
  {{- end }}
  {{- if .Values.exporter.github.privateKey }}
  privateKey: {{ .Values.exporter.github.privateKey | b64enc | quote }}
  {{- end }}
...
