---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "github-rate-limits-exporter.fullname" . }}
  labels:
    {{- include "github-rate-limits-exporter.labels" . | nindent 4 }}
    {{- if .Values.service.labels }}
    {{- toYaml .Values.service.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.service.annotations }}
  annotations:
  {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port | int }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "github-rate-limits-exporter.selectorLabels" . | nindent 4 }}
...
