---
name: Static code analysis, Testing, Container building and delivering (CI).
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}

env:
  DOCKERHUB_REPO: "theodore86/prometheus-gh-rate-limit-exporter"
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  linting_and_testing:
    uses: ./.github/workflows/linting-and-testing.yml
  build_and_publish_docker_image:
    needs: ["linting_and_testing"]
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout SCM"
        uses: "actions/checkout@v3.1.0"

      - name: "Login to docker registry"
        if: github.ref_type == 'tag'
        uses: "docker/login-action@v2.1.0"
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}
          logout: true

      - name: "Latest commit SHA as image tag"
        if: startsWith(github.ref, 'refs/heads/')
        run: |
          short_sha=$(git log -1 --format=%h)
          echo "DOCKER_TAG=$short_sha" >> $GITHUB_ENV

      - name: "Set pushed GIT TAG as image tag"
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo "DOCKER_TAG=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: "Build and Push docker image"
        uses: "docker/build-push-action@v3.2.0"
        with:
          push: ${{ github.ref_type == 'tag' }}
          context: .
          file: Dockerfile
          no-cache: true
          tags: |
            ${{ env.DOCKERHUB_REPO }}:${{ env.DOCKER_TAG }}
            ${{ env.DOCKERHUB_REPO }}:latest
